method=repeat
matchTiles=westerosblocks:textures/block/roofing/imbrex/imbrex_tegula_10_top
tiles=repeat10_top/0 repeat10_top/1 repeat10_top/2 repeat10_top/3 repeat10_top/4 repeat10_top/5 repeat10_top/6 repeat10_top/7 repeat10_top/8
width=3
height=3
