method=repeat
matchTiles=westerosblocks:textures/block/roofing/imbrex/imbrex_tegula_2_top
tiles=repeat2_top/0 repeat2_top/1 repeat2_top/2 repeat2_top/3 repeat2_top/4 repeat2_top/5 repeat2_top/6 repeat2_top/7 repeat2_top/8
width=3
height=3
