method=repeat
matchTiles=westerosblocks:textures/block/roofing/imbrex/imbrex_tegula_10
tiles=repeat10/0 repeat10/1 repeat10/2 repeat10/3 repeat10/4 repeat10/5 repeat10/6 repeat10/7 repeat10/8
width=3
height=3
