method=repeat
matchTiles=westerosblocks:textures/block/roofing/imbrex/imbrex_tegula_3_top
tiles=repeat3_top/0 repeat3_top/1 repeat3_top/2 repeat3_top/3 repeat3_top/4 repeat3_top/5 repeat3_top/6 repeat3_top/7 repeat3_top/8
width=3
height=3
