method=repeat
matchTiles=westerosblocks:textures/block/roofing/imbrex/imbrex_tegula_9_top
tiles=repeat9_top/0 repeat9_top/1 repeat9_top/2 repeat9_top/3 repeat9_top/4 repeat9_top/5 repeat9_top/6 repeat9_top/7 repeat9_top/8
width=3
height=3
