method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_12_top
tiles=repeat12_top/0 repeat12_top/1 repeat12_top/2 repeat12_top/3 repeat12_top/4 repeat12_top/5 repeat12_top/6 repeat12_top/7 repeat12_top/8
width=3
height=3
