method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_11
tiles=repeat11/0 repeat11/1 repeat11/2 repeat11/3 repeat11/4 repeat11/5 repeat11/6 repeat11/7 repeat11/8
width=3
height=3
