method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_11_top
tiles=repeat11_top/0 repeat11_top/1 repeat11_top/2 repeat11_top/3 repeat11_top/4 repeat11_top/5 repeat11_top/6 repeat11_top/7 repeat11_top/8
width=3
height=3
