method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_12
tiles=repeat12/0 repeat12/1 repeat12/2 repeat12/3 repeat12/4 repeat12/5 repeat12/6 repeat12/7 repeat12/8
width=3
height=3
