method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_14_top
tiles=repeat14_top/0 repeat14_top/1 repeat14_top/2 repeat14_top/3 repeat14_top/4 repeat14_top/5 repeat14_top/6 repeat14_top/7 repeat14_top/8
width=3
height=3
