method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_16
tiles=repeat16/0 repeat16/1 repeat16/2 repeat16/3 repeat16/4 repeat16/5 repeat16/6 repeat16/7 repeat16/8
width=3
height=3
