method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_13_top
tiles=repeat13_top/0 repeat13_top/1 repeat13_top/2 repeat13_top/3 repeat13_top/4 repeat13_top/5 repeat13_top/6 repeat13_top/7 repeat13_top/8
width=3
height=3
