method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_5_top
tiles=repeat5_top/0 repeat5_top/1 repeat5_top/2 repeat5_top/3 repeat5_top/4 repeat5_top/5 repeat5_top/6 repeat5_top/7 repeat5_top/8
width=3
height=3
