method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_14
tiles=repeat14/0 repeat14/1 repeat14/2 repeat14/3 repeat14/4 repeat14/5 repeat14/6 repeat14/7 repeat14/8
width=3
height=3
