method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_13
tiles=repeat13/0 repeat13/1 repeat13/2 repeat13/3 repeat13/4 repeat13/5 repeat13/6 repeat13/7 repeat13/8
width=3
height=3
