method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_1_top
tiles=repeat1_top/0 repeat1_top/1 repeat1_top/2 repeat1_top/3 repeat1_top/4 repeat1_top/5 repeat1_top/6 repeat1_top/7 repeat1_top/8
width=3
height=3
