method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_15
tiles=repeat15/0 repeat15/1 repeat15/2 repeat15/3 repeat15/4 repeat15/5 repeat15/6 repeat15/7 repeat15/8
width=3
height=3
