method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_17_top
tiles=repeat17_top/0 repeat17_top/1 repeat17_top/2 repeat17_top/3 repeat17_top/4 repeat17_top/5 repeat17_top/6 repeat17_top/7 repeat17_top/8
width=3
height=3
