method=repeat
matchTiles=westerosblocks:textures/block/roofing/shingle/wood_shingle_17
tiles=repeat17/0 repeat17/1 repeat17/2 repeat17/3 repeat17/4 repeat17/5 repeat17/6 repeat17/7 repeat17/8
width=3
height=3
