method=vertical
matchTiles=westerosblocks:textures/block/flowers/meadow_fescue/side1
connect=block
layer=cutout
tiles=side1_default/0 side1_default/1 side1_default/2 side1_default/3
biomes=!minecraft:old_growth_pine_taiga minecraft:ice_spikes minecraft:windswept_gravelly_hills minecraft:old_growth_spruce_taiga minecraft:frozen_river minecraft:windswept_hills minecraft:taiga minecraft:snowy_taiga minecraft:windswept_forest minecraft:frozen_ocean minecraft:snowy_plains minecraft:snowy_beach