method=repeat
matchTiles=westerosblocks:textures/block/wood/grey_blue/vertical
tiles=vertical/0 vertical/1 vertical/2 vertical/3 vertical/4 vertical/5 vertical/6 vertical/7 vertical/8
width=3
height=3