method=repeat
matchTiles=westerosblocks:textures/block/pebble/stormlands/light
tiles=repeat_light/0 repeat_light/1 repeat_light/2 repeat_light/3 repeat_light/4 repeat_light/5 repeat_light/6 repeat_light/7 repeat_light/8
width=3
height=3
