method=repeat
matchTiles=westerosblocks:textures/block/pebble/westerlands/dark
tiles=repeat_dark/0 repeat_dark/1 repeat_dark/2 repeat_dark/3 repeat_dark/4 repeat_dark/5 repeat_dark/6 repeat_dark/7 repeat_dark/8
width=3
height=3
