method=vertical
matchTiles=westerosblocks:textures/block/timber/northern/close_studding
connect_to_states=connectstate
layer=cutout
tiles=close_studding/0 close_studding/1 close_studding/2 close_studding/3