method=ctm
matchTiles=minecraft:textures/block/birch_planks
connect_to_tag=westerosblocks:plank_ctm
tiles=birch_planks/repeat_lined/0 birch_planks/repeat_lined/1 birch_planks/repeat_lined/2 birch_planks/repeat_lined/3 birch_planks/repeat_lined/4 birch_planks/repeat_lined/5 birch_planks/repeat_lined/6 birch_planks/repeat_lined/7 birch_planks/repeat_lined/8
width=3
height=3