method=repeat
matchTiles=minecraft:textures/block/jungle_planks
connect_to_tag=westerosblocks:plank_ctm
width=3
height=3
tiles=jungle_planks/repeat_lined/0 jungle_planks/repeat_lined/1 jungle_planks/repeat_lined/2 jungle_planks/repeat_lined/3 jungle_planks/repeat_lined/4 jungle_planks/repeat_lined/5 jungle_planks/repeat_lined/6 jungle_planks/repeat_lined/7 jungle_planks/repeat_lined/8