method=repeat
matchTiles=minecraft:textures/block/oak_planks
connect_to_tag=westerosblocks:plank_ctm
tiles=oak_planks/repeat_lined/0 oak_planks/repeat_lined/1 oak_planks/repeat_lined/2 oak_planks/repeat_lined/3 oak_planks/repeat_lined/4 oak_planks/repeat_lined/5 oak_planks/repeat_lined/6 oak_planks/repeat_lined/7 oak_planks/repeat_lined/8
width=3
height=3