method=repeat
matchTiles=minecraft:textures/block/spruce_planks
connect_to_tag=westerosblocks:plank_ctm
tiles=spruce_planks/repeat_lined/0 spruce_planks/repeat_lined/1 spruce_planks/repeat_lined/2 spruce_planks/repeat_lined/3 spruce_planks/repeat_lined/4 spruce_planks/repeat_lined/5 spruce_planks/repeat_lined/6 spruce_planks/repeat_lined/7 spruce_planks/repeat_lined/8
width=3
height=3