method=horizontal
matchTiles=minecraft:textures/block/red_sandstone/red_sandstone
connect=block
tiles=red_sandstone_a/0 red_sandstone_a/1 red_sandstone_a/2 red_sandstone_a/3
biomes=minecraft:ocean minecraft:mushroom_fields minecraft:ice_spikes minecraft:mushroom_field_shore minecraft:desert_hills minecraft:jungle_edge minecraft:forest minecraft:taiga_hills minecraft:frozen_ocean minecraft:desert minecraft:swamp