method=repeat
matchTiles=westerosblocks:textures/block/terrainset/north/light_snow/all
tiles=light_snow/0 light_snow/1 light_snow/2 light_snow/3 light_snow/4 light_snow/5 light_snow/6 light_snow/7 light_snow/8 light_snow/9 light_snow/10 light_snow/11 light_snow/12 light_snow/13 light_snow/14 light_snow/15
width=4
height=4