method=repeat
matchTiles=westerosblocks:textures/block/wood/orange/all_lines
tiles=repeat_lined/0 repeat_lined/1 repeat_lined/2 repeat_lined/3 repeat_lined/4 repeat_lined/5 repeat_lined/6 repeat_lined/7 repeat_lined/8
width=3
height=3