method=repeat
matchTiles=westerosblocks:textures/block/terrainset/north_alt/heavy_snow/all
tiles=heavy_snow/0 heavy_snow/1 heavy_snow/2 heavy_snow/3 heavy_snow/4 heavy_snow/5 heavy_snow/6 heavy_snow/7 heavy_snow/8 heavy_snow/9 heavy_snow/10 heavy_snow/11 heavy_snow/12 heavy_snow/13 heavy_snow/14 heavy_snow/15
width=4
height=4