method=repeat
matchTiles=westerosblocks:textures/block/terrainset/north_alt/medium_snow/all
tiles=medium_snow/0 medium_snow/1 medium_snow/2 medium_snow/3 medium_snow/4 medium_snow/5 medium_snow/6 medium_snow/7 medium_snow/8 medium_snow/9 medium_snow/10 medium_snow/11 medium_snow/12 medium_snow/13 medium_snow/14 medium_snow/15
width=4
height=4