method=repeat
matchTiles=westerosblocks:textures/block/terrainset/north_alt/medium_snow/all
tiles=medium_snow/0 medium_snow/1 medium_snow/2 medium_snow/3 medium_snow/4 medium_snow/5 medium_snow/6 medium_snow/7 medium_snow/8
width=3
height=3