method=repeat
matchTiles=westerosblocks:textures/block/terrainset/north_alt/snow/all
tiles=snow/0 snow/1 snow/2 snow/3 snow/4 snow/5 snow/6 snow/7 snow/8 snow/9 snow/10 snow/11 snow/12 snow/13 snow/14 snow/15
width=4
height=4