method=repeat
matchTiles=westerosblocks:textures/block/thatch/grey/all4_top
tiles=repeat4_top/0 repeat4_top/1 repeat4_top/2 repeat4_top/3 repeat4_top/4 repeat4_top/5 repeat4_top/6 repeat4_top/7 repeat4_top/8
width=3
height=3
