method=repeat
matchTiles=westerosblocks:textures/block/thatch/grey/all6_top
tiles=repeat6_top/0 repeat6_top/1 repeat6_top/2 repeat6_top/3 repeat6_top/4 repeat6_top/5 repeat6_top/6 repeat6_top/7 repeat6_top/8
width=3
height=3
