method=repeat
matchTiles=westerosblocks:textures/block/thatch/grey/all_top
tiles=repeat_top/0 repeat_top/1 repeat_top/2 repeat_top/3 repeat_top/4 repeat_top/5 repeat_top/6 repeat_top/7 repeat_top/8
width=3
height=3
