method=vertical
matchTiles=westerosblocks:textures/block/sausages_leg_of_ham/side2
layer=cutout
connect=block
biomes=minecraft:windswept_hills minecraft:windswept_forest minecraft:windswept_gravelly_hills minecraft:snowy_beach minecraft:taiga minecraft:snowy_taiga minecraft:old_growth_pine_taiga minecraft:old_growth_spruce_taiga minecraft:snowy_plains minecraft:frozen_river minecraft:frozen_ocean minecraft:ice_spikes
tiles=side2_cold/0 side2_cold/1 side2_cold/2 side2_cold/3
