method=repeat
matchTiles=westerosblocks:textures/block/fallen_leaves/temperate
tiles=temperate_a/0 temperate_a/1 temperate_a/2 temperate_a/3 temperate_a/4 temperate_a/5 temperate_a/6 temperate_a/7 temperate_a/8
width=3
height=3
biomes=minecraft:old_growth_pine_taiga minecraft:ice_spikes minecraft:windswept_gravelly_hills minecraft:snowy_slopes minecraft:old_growth_spruce_taiga minecraft:frozen_river minecraft:windswept_hills minecraft:taiga minecraft:snowy_taiga minecraft:windswept_forest minecraft:frozen_ocean minecraft:snowy_plains minecraft:snowy_beach