method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_dark
tiles=oak_dark/0 oak_dark/1 oak_dark/2 oak_dark/3 oak_dark/4 oak_dark/5 oak_dark/6 oak_dark/7 oak_dark/8
width=3
height=3
