method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_dark_top
tiles=oak_dark_top/0 oak_dark_top/1 oak_dark_top/2 oak_dark_top/3 oak_dark_top/4 oak_dark_top/5 oak_dark_top/6 oak_dark_top/7 oak_dark_top/8
width=3
height=3
