method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_deep_top
tiles=oak_deep_top/0 oak_deep_top/1 oak_deep_top/2 oak_deep_top/3 oak_deep_top/4 oak_deep_top/5 oak_deep_top/6 oak_deep_top/7 oak_deep_top/8
width=3
height=3
