method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_bleached
tiles=oak_bleached/0 oak_bleached/1 oak_bleached/2 oak_bleached/3 oak_bleached/4 oak_bleached/5 oak_bleached/6 oak_bleached/7 oak_bleached/8
width=3
height=3
