method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_light_top
tiles=oak_light_top/0 oak_light_top/1 oak_light_top/2 oak_light_top/3 oak_light_top/4 oak_light_top/5 oak_light_top/6 oak_light_top/7 oak_light_top/8
width=3
height=3
