method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_pale
tiles=oak_pale/0 oak_pale/1 oak_pale/2 oak_pale/3 oak_pale/4 oak_pale/5 oak_pale/6 oak_pale/7 oak_pale/8
width=3
height=3
