method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_deep
tiles=oak_deep/0 oak_deep/1 oak_deep/2 oak_deep/3 oak_deep/4 oak_deep/5 oak_deep/6 oak_deep/7 oak_deep/8
width=3
height=3
