method=repeat
matchTiles=westerosblocks:textures/block/roofing/beavertail/oak_light
tiles=oak_light/0 oak_light/1 oak_light/2 oak_light/3 oak_light/4 oak_light/5 oak_light/6 oak_light/7 oak_light/8
width=3
height=3
