method=fixed
matchTiles=westerosblocks:textures/block/deadbush/side4
layer=cutout
tiles=side4_e/0
biomes=minecraft:ocean minecraft:river minecraft:frozen_river minecraft:windswept_hills minecraft:taiga minecraft:frozen_ocean minecraft:snowy_plains minecraft:sparse_jungle