method=fixed
matchTiles=westerosblocks:textures/block/deadbush/side6
connect=block
layer=cutout
tiles=side6_default/0
biomes=!minecraft:ocean minecraft:mushroom_fields minecraft:snowy_plains minecraft:birch_forest minecraft:river minecraft:frozen_river minecraft:windswept_hills minecraft:jungle minecraft:taiga minecraft:old_growth_birch_forest minecraft:forest minecraft:beach minecraft:frozen_ocean minecraft:desert minecraft:swamp minecraft:sparse_jungle minecraft:plains